[tools]
bun = "latest"
"cargo:cargo-binstall" = "latest"
"cargo:cargo-edit" = "latest"
go = "latest"
hugo = "latest"
java = "21"
maven = "latest"
opencode = "latest"
prek = "latest"
rust = "latest"
usage = "latest"

[settings]

[settings.cargo]
binstall = true
