# [[language]]
# name = "python"
# language-servers = [ "basedpyright", "ruff" ]
# auto-format = true

# [language-server.ruff]
# command = "ruff"
# args = ["server"]

# [[language]]
# name = "markdown"
# language-servers = [ "markdown-oxide" ]

