rules:
 - IP-CIDR,192.168.1.1/32,DIRECT
 - DOMAIN,ipw.cn,DIRECT
 - DOMAIN,test-ipv6.com,DIRECT
 - DOMAIN,webofscience.clarivate.cn,ðŸŽ“å­¦æœ¯ç½‘ç«™
 - DOMAIN,sciencedirect.com,ðŸŽ“å­¦æœ¯ç½‘ç«™
 - DOMAIN,pdf.sciencedirect.com,ðŸŽ“å­¦æœ¯ç½‘ç«™
