# å¦‚æœVPNè¢«claudeè¯†ç ´äº†ï¼Œè€ƒè™‘å…³é—­chromeçš„QUICåè®®ï¼Œmihomoæ— æ³•è§£æ

tun:
  enable: true
  stack: system
  auto-route: true
  auto-redirect: false
  auto-detect-interface: true
  strict-route: true
  gso: false
  skip-proxy:
    - 10.100.0.0/24
    - 127.0.0.1/8
    - 'localhost'

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - tls://8.8.4.4
    - tls://1.1.1.1
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4

proxies:
  - {name: "æ ¡å›­ç½‘å‡ºå£", type: socks5, server: 10.100.0.2, port: 1080, interface-name: wg0}

proxy-groups:
  - name: "æ ¡å›­ç½‘èµ„æº"
    type: select
    proxies:
      - "æ ¡å›­ç½‘å‡ºå£"
      - "DIRECT"  # å¤‡é€‰é¡¹

rules:
 - DOMAIN-SUFFIX,gmail.com,ğŸ”° é€‰æ‹©èŠ‚ç‚¹ # è°·æ­Œé‚®ç®±æœåŠ¡
 - DOMAIN,webofscience.clarivate.cn,ğŸ“å­¦æœ¯ç½‘ç«™ # æ ¡å›­ç½‘ç›´è¿ç”¨è¿™ä¸ª

 # WireGuardè¿œç¨‹è®¿é—®
 # - DOMAIN,webofscience.clarivate.cn,æ ¡å›­ç½‘èµ„æº
 # - DOMAIN-SUFFIX,zendesk.com,æ ¡å›­ç½‘èµ„æº
 # - DOMAIN-SUFFIX,webofscience.com,æ ¡å›­ç½‘èµ„æº
 # - DOMAIN-SUFFIX,webofknowledge.com,æ ¡å›­ç½‘èµ„æº
 # - DOMAIN-SUFFIX,clarivate.com,æ ¡å›­ç½‘èµ„æº
 # - DOMAIN-SUFFIX,clarivate.cn,æ ¡å›­ç½‘èµ„æº
 # - DOMAIN-SUFFIX,isiknowledge.com,æ ¡å›­ç½‘èµ„æº
 # - DOMAIN-SUFFIX,thomsonreuters.com,æ ¡å›­ç½‘èµ„æº
 # - DOMAIN-SUFFIX,scientific-direct.com,æ ¡å›­ç½‘èµ„æº
 # - DOMAIN-SUFFIX,onetrust.com,æ ¡å›­ç½‘èµ„æº
 # - DOMAIN-SUFFIX,cookielaw.org,æ ¡å›­ç½‘èµ„æº
